"""create document and document_chunk tables

Revision ID: 38ea7f45f2db
Revises: 2c0b18c41f59
Create Date: 2026-08-07 18:17:05.436690

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '38ea7f45f2db'
down_revision: Union[str, Sequence[str], None] = '2c0b18c41f59'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('document_chunks', 'chunk_metadata',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False)
    op.add_column('documents', sa.Column('mime_type', sa.String(length=100), nullable=False))
    op.add_column('documents', sa.Column('checksum', sa.String(length=64), nullable=False))
    op.add_column('documents', sa.Column('version', sa.Integer(), nullable=False))
    op.add_column('documents', sa.Column('processed_at', sa.DateTime(), nullable=True))
    op.create_unique_constraint(None, 'documents', ['checksum'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'documents', type_='unique')
    op.drop_column('documents', 'processed_at')
    op.drop_column('documents', 'version')
    op.drop_column('documents', 'checksum')
    op.drop_column('documents', 'mime_type')
    op.alter_column('document_chunks', 'chunk_metadata',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               nullable=True)
    # ### end Alembic commands ###
